# Introduction

In this notebook I will be aggregating a median rental prices for 1 - 4 bedroom properties from zillow. This data pertains to the San Francisco(SF) area from March of 2010 through November of 2019.

In [64]:
#Read in libraries
import pandas as pd
import glob

import os

In [65]:
#Increase number of columns and rows displayed by Pandas
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows',100)

#supress future warnings
import warnings; warnings.simplefilter(action='ignore', category=FutureWarning)

In [66]:
#Set path to location of zillow raw data on local machine
path = r'C:\Users\kishe\Documents\Data Science\Projects\Python Projects\In Progress\Air BnB - SF\Data\01_Raw\Zillow Raw Data/'

#Change wd to path to zillow data location
os.chdir(path)

In [67]:
#Get current directory csv files
csvs = [x for x in os.listdir('.') if x.endswith('.csv')]

#stats.csv -> stats
fns = [os.path.splitext(os.path.basename(x))[0] for x in csvs]

#Create empty dictionary
d = {}

#Store csv data in d
for i in range(len(fns)):
    d[fns[i]] = pd.read_csv(csvs[i])

In [68]:
#Assign data to seperate data frames
one_br = d['Zip_MedianRentalPrice_1Bedroom']
two_br = d['Zip_MedianRentalPrice_2Bedroom']
three_br = d['Zip_MedianRentalPrice_3Bedroom']
four_br = d['Zip_MedianRentalPrice_4Bedroom']

**Preview Dataframes**

In [69]:
#Check shape of data frame
print('Shape of one_br: ', one_br.shape)

#Preview Data
display(one_br.head())

Shape of one_br:  (1676, 117)

,RegionName,City,State,Metro,CountyName,SizeRank,2010-09,2010-10,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11
0,10025,New York,NY,New York-Newark-Jersey City,New York County,1,NaN,2600.0,2689.0,2678.0,2400.0,2392.5,2450.0,2495.0,2550.0,2550.0,2500.0,2495.0,2395.0,2425.0,2595.0,2640.0,2500.0,2500.0,2500.0,2550.0,2590.0,2595.0,2625.0,2697.0,2700.0,2800.0,2850.0,2750.0,2732.5,2695.0,2695.0,2730.0,2800.0,2809.0,2700.0,2700.0,2878.5,2800.0,2800.0,2850.0,2900.0,2900.0,2900.0,2850.0,2800.0,2750.0,3200.0,3050.0,3100.0,3075.0,3100.0,3100.0,3100.0,3088.0,3100.0,3100.0,3000.0,2962.5,2997.5,3050.0,3097.5,3050.0,3050.0,3000.0,3050.0,3050.0,3100.0,3000.0,3100.0,3050.0,3000.0,3000.0,3100.0,3050.0,3012.5,2950.0,3032.5,3000.0,3000.0,2995.0,2975.0,2900.0,2900.0,3025.0,3025.0,3000.0,2935.0,3025.0,3032.5,3040.5,2995.0,2975.0,2995.0,3000.0,2950.0,2900.0,2900.0,2950.0,3000.0,3100.0,3150.0,3195.0,3200.0,3200.0,3100.0,3150.0,3100.0,3100.0,3050.0,3100.0,3156.0
1,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,2,NaN,NaN,NaN,NaN,1075.0,1095.0,1095.0,1080.0,1110.0,1125.0,1125.0,1095.0,1095.0,1100.0,1105.0,1125.0,1125.0,1100.0,1100.0,1125.0,1125.0,1145.0,1125.0,1095.0,1105.0,1147.5,1150.0,1175.0,1195.0,1205.0,1199.0,1200.0,1220.0,1230.0,1250.0,1270.0,1250.0,1245.0,1245.0,1245.0,1245.0,1250.0,1250.0,1250.0,1270.0,1265.0,1275.0,1275.0,1250.0,1250.0,1252.5,1255.0,1265.0,1295.0,1295.0,1300.0,1305.0,1325.0,1315.0,1295.0,1295.0,1295.0,1300.0,1312.5,1325.0,1345.0,1395.0,1395.0,1395.0,1400.0,1395.0,1375.0,1340.0,1350.0,1295.0,1295.0,1350.0,1450.0,1450.0,1450.0,1450.0,1465.0,1450.0,1420.0,1400.0,1375.0,1370.0,1386.0,1400.0,1440.0,1425.0,1445.0,1450.0,1450.0,1450.0,1400.0,1370.0,1350.0,1350.0,1395.0,1450.0,1425.0,1475.0,1490.0,1475.0,1495.0,1452.5,1425.0,1425.0,1410.0,1400.0
2,10023,New York,NY,New York-Newark-Jersey City,New York County,3,NaN,2995.0,3025.0,3000.0,2770.0,2835.0,2900.0,3000.0,3000.0,2850.0,2900.0,2900.0,2950.0,2999.5,3100.0,3150.0,3100.0,3070.0,3000.0,3000.0,3100.0,3000.0,3000.0,3000.0,3100.0,3117.5,3100.0,3037.5,3000.0,3000.0,3150.0,3047.0,3042.0,3100.0,3109.0,3150.0,3200.0,3200.0,3100.0,3195.0,3200.0,3200.0,3200.0,3199.0,3200.0,3175.0,3295.0,3337.5,3300.0,3300.0,3350.0,3300.0,3300.0,3300.0,3350.0,3369.0,3300.0,3300.0,3337.5,3350.0,3350.0,3300.0,3300.0,3300.0,3300.0,3300.0,3300.0,3300.0,3300.0,3300.0,3100.0,3300.0,3300.0,3300.0,3300.0,3300.0,3226.0,3295.0,3250.0,3300.0,3299.5,3300.0,3300.0,3295.0,3290.5,3295.0,3300.0,3300.0,3259.0,3250.0,3225.0,3285.0,3300.0,3300.0,3300.0,3300.0,3300.0,3300.0,3295.0,3300.0,3300.0,3300.0,3300.0,3350.0,3350.0,3325.0,3297.5,3350.0,3350.0,3400.0,3391.5
3,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1042.0,1058.0,1010.0,1010.0,1010.0,1055.0,1078.0,1022.0,1078.0,1088.0,1080.0,1055.0,1052.0,1050.0,1034.0,1000.0,1000.0,980.0,1032.5,1004.5,1019.5,1005.0,985.0,1021.0,1020.0,1020.0,1020.0,1063.5,1000.0,1000.0,985.0,1029.0,1039.0,1205.0,1057.0,1095.0,1104.0,1127.0,1225.0,1175.0,1082.0,1045.0,1081.0,1058.0,1119.0,1134.5,1097.0,1119.0,1175.0,1165.0,1124.0,1190.0,1202.5,1179.0,1175.0,1179.0,1175.0,1190.0,1205.0,1200.0,1178.0,1209.0,1209.0,1177.0,1245.0,1213.0,1144.0,1159.0,1159.0,1155.0,1152.5,1194.0,1236.5,1201.0,1206.0,1169.0,1157.0,1127.5
4,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,5,NaN,NaN,NaN,NaN,1250.0,1200.0,1199.0,1175.0,1195.0,1245.0,1265.0,1260.0,1295.0,1300.0,1300.0,1375.0,1375.0,1365.0,1365.0,1350.0,1315.0,1400.0,1435.0,1485.0,1495.0,1495.0,1515.0,1545.0,1500.0,1492.5,1450.0,1450.0,1500.0,1497.5,1450.0,1445.0,1467.5,1450.0,1450.0,1550.0,1525.0,1495.0,1450.0,1435.0,1445.0,1425.0,1395.0,1395.0,1465.0,1500.0,1644.0,1500.0,1525.0,1485.0,1395.0,1475.0,1475.0,1450.0,1425.0,1435.0,1445.0,1425.0,1565.0,1575.0,1550.0,1666.0,1550.0,1525.0,1460.0,1460.0,1455.0,1525.0,1500.0,1450.0,1500.0,1500.0,1575.0,1550.0,1545.0,1495.0,1500.0,1500.0,1535.0,1551.0,1595.0,1595.0,1500.0,1545.0,1575.0,1610.0,1595.0,1600.0,1600.0,1595.0,1577.0,1595.0,1550.0,1550.0,1520.0,1600.0,1650.0,1650.0,1695.0,1675.0,1700.0,1675.0,1720.0,1700.0,1670.0,1625.0,1600.0

In [70]:
#Check shape of data frame
print('Shape of two_br: ', two_br.shape)

#Preview Data
display(two_br.head())

Shape of two_br:  (2540, 117)

,RegionName,City,State,Metro,CountyName,SizeRank,2010-09,2010-10,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11
0,10025,New York,NY,New York-Newark-Jersey City,New York County,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2850.0,2972.5,3172.5,3000.0,2995.0,3000.0,3000.0,3000.0,3195.0,3200.0,3000.0,3150.0,3400.0,3500.0,3500.0,3500.0,3350.0,3300.0,3400.0,3200.0,3200.0,3200.0,3100.0,3200.0,3295.0,3225.0,3250.0,3295.0,3300.0,3300.0,3350.0,3350.0,3350.0,3295.0,3500.0,3400.0,3692.5,3750.0,3725.0,3600.0,3599.0,3500.0,3500.0,3450.0,3499.0,3500.0,3500.0,3400.0,3600.0,3700.0,3690.0,3500.0,3681.0,3795.0,3534.0,3600.0,3522.5,3500.0,3400.0,3500.0,3595.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3500.0,3450.0,3400.0,3400.0,3500.0,3500.0,3645.0,3622.5,3600.0,3581.0,3500.0,3500.0,3550.0,3500.0,3500.0,3500.0,3500.0,3500.0,3525.0,3500.0,3550.0,3500.0,3495.0,3500.0,3600.0,3450.0,3399.5,3450.0,3500.0,3849.0,3952.5
1,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,2,NaN,NaN,NaN,NaN,1597.5,1575.0,1600.0,1600.0,1600.0,1675.0,1675.0,1600.0,1695.0,1700.0,1700.0,1695.0,1675.0,1600.0,1600.0,1600.0,1625.0,1695.0,1700.0,1695.0,1800.0,1820.0,1820.0,1800.0,1795.0,1750.0,1650.0,1700.0,1700.0,1795.0,1795.0,1785.0,1800.0,1850.0,1900.0,1850.0,1800.0,1800.0,1795.0,1725.0,1750.0,1775.0,1795.0,1770.0,1750.0,1795.0,1775.0,1750.0,1795.0,1795.0,1740.0,1800.0,1795.0,1825.0,1820.0,1825.0,1809.5,1800.0,1800.0,1800.0,1875.0,1850.0,1895.0,1880.0,1850.0,1900.0,1900.0,1857.5,1890.0,1850.0,1800.0,1800.0,1900.0,1950.0,1975.0,1900.0,1935.0,1945.0,1925.0,1920.0,1895.0,1849.5,1850.0,1800.0,1850.0,1900.0,1950.0,1950.0,1945.0,1925.0,1950.0,1900.0,1850.0,1800.0,1800.0,1840.0,1895.0,1901.0,1950.0,1950.0,1950.0,1958.5,1990.0,1950.0,1950.0,1900.0,1895.0
2,10023,New York,NY,New York-Newark-Jersey City,New York County,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5120.0,5200.0,5100.0,5060.0,4975.0,5195.0,4925.0,5000.0,5372.5,5200.0,5000.0,4937.5,5000.0,5069.5,4900.0,4975.0,5000.0,5046.5,5000.0,4987.5,4912.5,4995.0,4900.0,4625.0,4962.5,4900.0,4800.0,4867.5,4800.0,4800.0,4900.0,4897.5,4900.0,4950.0,4900.0,4900.0,4800.0,5000.0,5075.0,5000.0,4950.0,5060.0,5200.0,4937.5,4800.0,4925.0,4950.0,4937.5,4995.0,5000.0,5000.0,4925.0,4800.0,4800.0,4860.0,4750.0,4840.0,4900.0,4900.0,4950.0,5200.0,5183.5,5400.0,5200.0
3,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1466.0,1466.0,1486.5,1482.0,1443.5,1430.5,1425.0,1439.0,1436.0,1675.0,1562.5,1450.0,1547.5,1528.0,1582.0,1557.5,1552.5,1520.0,1524.0,1437.5,1528.0,1489.0,1459.5,1526.5,1600.0,1604.5,1590.0,1627.5,1610.0,1639.5,1634.5,1650.0,1645.0,1656.0,1656.0,1630.0,1650.0,1619.0,1600.0,1620.0,1609.0,1699.0,1649.5,1672.0,1665.0,1659.0,1599.0,1605.0,1619.0,1619.0,1600.0,1590.0,1590.0,1578.0
4,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,5,NaN,NaN,NaN,NaN,NaN,1700.0,1700.0,1650.0,1665.0,1740.0,1785.0,1800.0,1810.0,1900.0,1900.0,1950.0,1950.0,1875.0,1812.5,1865.0,1895.0,2000.0,2040.0,2275.0,2350.0,2400.0,2300.0,2355.0,2200.0,2100.0,1860.0,1975.0,2000.0,1995.0,1950.0,2035.0,2100.0,2100.0,2200.0,2230.0,2200.0,2100.0,2100.0,1995.0,1899.0,1995.0,2000.0,1995.0,2000.0,2000.0,2100.0,2095.0,2100.0,1995.0,1840.0,1995.0,1995.0,1995.0,1950.0,1995.0,1999.0,1999.0,2097.0,2029.0,2029.0,2202.5,2177.5,2065.0,2000.0,2055.0,1995.0,2000.0,1995.0,2055.0,1975.0,2000.0,2015.0,2060.0,2050.0,2067.5,2075.0,2050.0,2095.0,2010.0,2010.0,2000.0,2010.0,2070.0,2100.0,2089.0,2135.0,2150.0,2100.0,2100.0,2100.0,2095.0,2000.0,2100.0,2150.0,2200.0,2350.0,2350.0,2300.0,2200.0,2200.0,2155.0,2150.0,2245.0,2390.0,2300.0,2316.0

In [71]:
#Check shape of data frame
print('Shape of three_br: ', three_br.shape)

#Preview Data
display(three_br.head())

Shape of three_br:  (1594, 123)

,RegionName,City,State,Metro,CountyName,SizeRank,2010-03,2010-04,2010-05,2010-06,2010-07,2010-08,2010-09,2010-10,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11
0,10025,New York,NY,New York-Newark-Jersey City,New York County,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4037.5,4200.0,4075.0,3995.0,3600.0,3790.0,4037.5,3995.0,4200.0,4325.0,4395.0,4150.0,4100.0,4200.0,4200.0,4200.0,4200.0,4255.0,4550.0,4700.0,4700.0,4500.0,4500.0,4500.0,4500.0,4500.0,4400.0,4400.0,4351.0,4250.0,4000.0,4300.0,4400.0,4312.5,4362.5,4395.0,4495.0,4495.0,4372.5,4200.0,4500.0,4495.0,4500.0,4450.0,4475.0,4350.0,4450.0,4750.0,4650.0,4272.5,4400.0,4500.0,4350.0,4500.0,4300.0,4295.0,4295.0,4300.0,4300.0,4300.0,4300.0,4372.5,4350.0,4400.0,4400.0,4400.0,4246.0,4450.0,4395.0,4300.0,4500.0,4400.0,4475.0,4457.5,4300.0,4295.0,4250.0,4295.0,4424.5,4499.0,4350.0,4497.0,4300.0,4447.5,4495.0,4400.0,4449.0,4400.0,4300.0,4197.5,4300.0,4299.0,4192.0,4256.0,4575.0,4450.0,4500.0,4425.0,4350.0,4299.0,4300.0,4350.0,4300.0,4335.0,4550.0,4550.0
1,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2200.0,2285.0,2300.0,2250.0,2250.0,2345.0,2350.0,2350.0,2495.0,2400.0,2400.0,2200.0,2400.0,2400.0,2350.0,2300.0,2300.0,2400.0,2425.0,2562.5,2500.0,2662.5,2600.0,2562.5,2550.0,2562.5,2300.0,2500.0,2575.0,2595.0,2600.0,2495.0,2495.0,2400.0,2400.0,2395.0,2400.0,2495.0,2495.0,2495.0,2600.0,2600.0,2550.0,2500.0,2500.0,2495.0,2462.5,2500.0,2500.0,2500.0,2395.0,2550.0,2600.0,2600.0,2600.0,2500.0,2495.0,2400.0,2400.0,2450.0,2500.0,2600.0,2600.0,2600.0,2650.0,2650.0,2650.0,2600.0,2600.0,2538.0,2400.0,2550.0,2500.0,2529.0,2695.0,2600.0,2695.0,2700.0,2685.0,2695.0,2595.0,2500.0,2460.0,2495.0,2500.0,2580.0,2600.0,2600.0,2650.0,2600.0,2595.0,2500.0,2450.0,2395.0,2400.0,2350.0,2300.0,2350.0,2500.0,2600.0,2650.0,2660.0,2600.0,2550.0,2550.0,2495.0,2495.0
2,10023,New York,NY,New York-Newark-Jersey City,New York County,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8000.0,7842.0,7615.0,7631.5,7700.0,6995.0,6525.0,6719.5,6995.0,6900.0,6900.0,6999.0,6995.0,6999.0,7288.0,6995.0,6895.0,6999.5,7000.0,6997.0,6997.0,6947.5,6947.5,6947.5,6900.0,6600.0,6947.5,6850.0,6500.0,7095.0,6900.0,7147.5,7381.0
3,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1700.0,1650.0,1650.0,1650.0,1650.0,1675.0,1750.0,1800.0,1800.0,1850.0,1796.0,1750.0,1795.0,1800.0,1809.0,1823.0,1823.0,1823.0,1823.0,1823.0,1800.0,1800.0,1850.0,1850.0,1850.0,1850.0,1842.5,1850.0,1850.0,1829.0,1833.0,1833.0,1879.5,1875.0,1875.0,1850.0,1895.0,1900.0,1847.5,1832.5,1817.5,1850.0,1800.0,1800.0,1815.0,1800.0,1800.0,1850.0,1797.5,1800.0,1767.5,1700.0,1800.0,1750.0,1785.0,1750.0,1759.0,1769.0,1800.0,1802.5,1800.0,1800.0,1890.0,1850.0,1850.0,1855.0,1857.0,1889.0,1879.0,1889.5,1850.0,1869.0,1850.0,1800.0,1850.0,1850.0,1840.0,1840.0,1850.0,1844.0,1830.0,1849.0,1850.0,1849.5,1850.0,1849.0,1825.0,1850.0
4,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2400.0,2375.0,2395.0,2295.0,2175.0,2400.0,2497.5,2495.0,2495.0,2495.0,2500.0,2400.0,2497.0,2400.0,2400.0,2350.0,2400.0,2600.0,2600.0,2775.0,2700.0,2900.0,3000.0,2800.0,2700.0,2700.0,2400.0,2600.0,2600.0,2700.0,2650.0,2675.0,2550.0,2500.0,2500.0,2550.0,2600.0,2600.0,2550.0,2600.0,2695.0,2700.0,2700.0,2600.0,2500.0,2500.0,2700.0,2700.0,2750.0,2725.0,2450.0,2695.0,2790.0,2800.0,2795.0,2795.0,2800.0,2825.0,2800.0,2795.0,2850.0,2875.0,2950.0,2800.0,2800.0,2950.0,2850.0,2895.0,2800.0,2800.0,2800.0,2800.0,2697.5,2900.0,2812.5,2850.0,2950.0,2995.0,2850.0,2850.0,2800.0,2700.0,2695.0,2695.0,2750.0,2850.0,2850.0,2850.0,2850.0,2850.0,2800.0,2800.0,2850.0,2850.0,2895.0,2895.0,2895.0,2800.0,2970.0,2901.0,2950.0,2950.0,2895.0,2850.0,2850.0,2875.0,2850.0

In [72]:
#Check shape of data frame
print('Shape of four_br: ', four_br.shape)

#Preview Data
display(four_br.head())

Shape of four_br:  (231, 113)

,RegionName,City,State,Metro,CountyName,SizeRank,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11
0,10025,New York,NY,New York-Newark-Jersey City,New York County,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5000.0,4795.0,4962.5,5195.0,5500.0,5400.0,5200.0,5375.0,5095.0,5000.0,5000.0,5000.0,4875.0,4850.0,5000.0,5200.0,5400.0,5487.5,5300.0,5650.0,5600.0,5175.0,5000.0,5200.0,5650.0,5700.0,5600.0,5425.0,5350.0,5000.0,5400.0,5175.0,5500.0,5500.0,5350.0,5500.0,5500.0,5500.0,5000.0,5175.0,5000.0,5095.5,5150.0,5000.0,4895.0,4800.0,4800.0,4897.5,5000.0,5150.0,5000.0,5000.0,4947.5,4900.0,4847.5,4800.0,4895.0,5000.0,4800.0,5000.0,5000.0,4947.5,5000.0,5000.0,4806.0,4812.0,4967.5,4823.0,4997.5,4847.5,4800.0,4945.0,4895.0,5175.0,5125.0,5300.0,5000.0,4800.0,4800.0,4800.0,4743.5,4800.0,4895.0,4800.0,4847.5,4800.0,4847.5,4997.5,5000.0,5000.0,4900.0,4800.0,4500.0,4550.0
1,60657,Chicago,IL,Chicago-Naperville-Elgin,Cook County,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3195.0,3172.5,3087.5,3000.0,2950.0,3000.0,3150.0,3100.0,3000.0,2972.5,2972.5,3025.0,3025.0,2900.0,3200.0,3200.0,3200.0,3600.0,3600.0,3400.0,3400.0,3599.5,3400.0,3400.0,3400.0,3200.0,3200.0,3200.0,3445.0,3400.0,3200.0,3050.0,2995.0,2997.5,3000.0,3095.0,3195.0,3095.0,3495.0,3600.0,3600.0,3337.5,3200.0,3095.0,3100.0,3100.0,3147.5,3195.0,3195.0,3195.0,3400.0,3450.0,3595.0,3300.0,3200.0,3300.0,3200.0,3400.0,3250.0,3300.0,3200.0,3300.0,3500.0,3600.0,3755.0,3600.0,3475.0,3395.0,3030.0,3090.0,3197.5,3200.0,3200.0,3587.5,3600.0,3650.0,3800.0,3695.0,3400.0,3200.0,3200.0,2950.0,3200.0,3450.0,3540.0,3570.0,3695.0,3800.0,3800.0,3995.0,3600.0,3600.0,3600.0,3200.0
2,77494,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2100.0,2025.0,2000.0,2115.0,2275.0,2375.0,2250.0,2300.0,2497.5,2300.0,2225.0,2100.0,2200.0,2347.5,2300.0,2372.5,2350.0,2300.0,2200.0,2200.0,2200.0,2300.0,2300.0,2290.0,2250.0,2200.0,2250.0,2300.0,2300.0,2300.0,2397.5,2400.0,2300.0,2400.0,2397.5,2350.0,2300.0,2300.0,2350.0,2350.0,2375.0,2400.0,2400.0,2400.0,2400.0,2350.0,2300.0,2350.0,2275.0,2298.0,2200.0,2250.0,2295.0,2400.0,2300.0,2300.0,2200.0,2150.0,2300.0,2197.5,1999.0,2175.0,2095.0,2162.5,2100.0,2200.0,2200.0,2200.0,2200.0,2250.0,2300.0,2400.0,2400.0,2400.0,2300.0,2300.0,2289.5,2287.5,2300.0,2280.0,2250.0,2195.0,2195.0,2150.0,2200.0,2250.0,2200.0,2200.0,2225.0,2250.0,2250.0,2300.0,2250.0,2200.0,2200.0,2200.0,2250.0
3,60614,Chicago,IL,Chicago-Naperville-Elgin,Cook County,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3450.0,3825.0,3750.0,3800.0,3995.0,3995.0,3800.0,3600.0,3600.0,3650.0,3300.0,3300.0,3300.0,3300.0,3300.0,3735.0,4100.0,3995.0,3985.0,3610.0,3600.0,3377.0,3300.0,3600.0,3895.0,3695.0,3600.0,3900.0,3995.0,3995.0,3995.0,3900.0,3900.0,3647.5,3600.0
4,77449,Katy,TX,Houston-The Woodlands-Sugar Land,Harris County,5,NaN,NaN,NaN,NaN,NaN,NaN,1300.0,1300.0,1350.0,1350.0,1325.0,1312.5,1350.0,1350.0,1350.0,1337.5,1350.0,1300.0,1312.5,1350.0,1362.5,1395.0,1400.0,1400.0,1462.5,1450.0,1450.0,1495.0,1485.0,1495.0,1500.0,1525.0,1500.0,1525.0,1500.0,1497.5,1450.0,1450.0,1450.0,1475.0,1500.0,1500.0,1595.0,1550.0,1525.0,1525.0,1550.0,1525.0,1525.0,1525.0,1550.0,1550.0,1550.0,1545.0,1537.5,1550.0,1600.0,1595.0,1550.0,1525.0,1525.0,1525.0,1550.0,1550.0,1597.5,1595.0,1600.0,1550.0,1525.0,1500.0,1475.0,1462.5,1450.0,1460.0,1485.0,1500.0,1535.0,1535.0,1550.0,1500.0,1550.0,1570.0,1550.0,1550.0,1500.0,1550.0,1557.5,1621.5,1600.0,1650.0,1600.0,1600.0,1600.0,1600.0,1575.0,1595.0,1577.5,1599.0,1595.0,1599.5,1600.0,1600.0,1622.5,1610.0,1625.0,1630.0,1650.0

**Add Bedroom Count**

In [73]:
#Assign beds column to differentiate data downstream
one_br['beds'] = 1
two_br['beds'] = 2
three_br['beds'] = 3
four_br['beds'] = 4

**Concatenate Data**

In [74]:
#Concatenate and assign to zillow
zillow = pd.concat([one_br,two_br,three_br,four_br], axis =0 )

#Preview
display(zillow.head())

,2010-03,2010-04,2010-05,2010-06,2010-07,2010-08,2010-09,2010-10,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,City,CountyName,Metro,RegionName,SizeRank,State,beds
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2600.0,2689.0,2678.0,2400.0,2392.5,2450.0,2495.0,2550.0,2550.0,2500.0,2495.0,2395.0,2425.0,2595.0,2640.0,2500.0,2500.0,2500.0,2550.0,2590.0,2595.0,2625.0,2697.0,2700.0,2800.0,2850.0,2750.0,2732.5,2695.0,2695.0,2730.0,2800.0,2809.0,2700.0,2700.0,2878.5,2800.0,2800.0,2850.0,2900.0,2900.0,2900.0,2850.0,2800.0,2750.0,3200.0,3050.0,3100.0,3075.0,3100.0,3100.0,3100.0,3088.0,3100.0,3100.0,3000.0,2962.5,2997.5,3050.0,3097.5,3050.0,3050.0,3000.0,3050.0,3050.0,3100.0,3000.0,3100.0,3050.0,3000.0,3000.0,3100.0,3050.0,3012.5,2950.0,3032.5,3000.0,3000.0,2995.0,2975.0,2900.0,2900.0,3025.0,3025.0,3000.0,2935.0,3025.0,3032.5,3040.5,2995.0,2975.0,2995.0,3000.0,2950.0,2900.0,2900.0,2950.0,3000.0,3100.0,3150.0,3195.0,3200.0,3200.0,3100.0,3150.0,3100.0,3100.0,3050.0,3100.0,3156.0,New York,New York County,New York-Newark-Jersey City,10025,1,NY,1
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1075.0,1095.0,1095.0,1080.0,1110.0,1125.0,1125.0,1095.0,1095.0,1100.0,1105.0,1125.0,1125.0,1100.0,1100.0,1125.0,1125.0,1145.0,1125.0,1095.0,1105.0,1147.5,1150.0,1175.0,1195.0,1205.0,1199.0,1200.0,1220.0,1230.0,1250.0,1270.0,1250.0,1245.0,1245.0,1245.0,1245.0,1250.0,1250.0,1250.0,1270.0,1265.0,1275.0,1275.0,1250.0,1250.0,1252.5,1255.0,1265.0,1295.0,1295.0,1300.0,1305.0,1325.0,1315.0,1295.0,1295.0,1295.0,1300.0,1312.5,1325.0,1345.0,1395.0,1395.0,1395.0,1400.0,1395.0,1375.0,1340.0,1350.0,1295.0,1295.0,1350.0,1450.0,1450.0,1450.0,1450.0,1465.0,1450.0,1420.0,1400.0,1375.0,1370.0,1386.0,1400.0,1440.0,1425.0,1445.0,1450.0,1450.0,1450.0,1400.0,1370.0,1350.0,1350.0,1395.0,1450.0,1425.0,1475.0,1490.0,1475.0,1495.0,1452.5,1425.0,1425.0,1410.0,1400.0,Chicago,Cook County,Chicago-Naperville-Elgin,60657,2,IL,1
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2995.0,3025.0,3000.0,2770.0,2835.0,2900.0,3000.0,3000.0,2850.0,2900.0,2900.0,2950.0,2999.5,3100.0,3150.0,3100.0,3070.0,3000.0,3000.0,3100.0,3000.0,3000.0,3000.0,3100.0,3117.5,3100.0,3037.5,3000.0,3000.0,3150.0,3047.0,3042.0,3100.0,3109.0,3150.0,3200.0,3200.0,3100.0,3195.0,3200.0,3200.0,3200.0,3199.0,3200.0,3175.0,3295.0,3337.5,3300.0,3300.0,3350.0,3300.0,3300.0,3300.0,3350.0,3369.0,3300.0,3300.0,3337.5,3350.0,3350.0,3300.0,3300.0,3300.0,3300.0,3300.0,3300.0,3300.0,3300.0,3300.0,3100.0,3300.0,3300.0,3300.0,3300.0,3300.0,3226.0,3295.0,3250.0,3300.0,3299.5,3300.0,3300.0,3295.0,3290.5,3295.0,3300.0,3300.0,3259.0,3250.0,3225.0,3285.0,3300.0,3300.0,3300.0,3300.0,3300.0,3300.0,3295.0,3300.0,3300.0,3300.0,3300.0,3350.0,3350.0,3325.0,3297.5,3350.0,3350.0,3400.0,3391.5,New York,New York County,New York-Newark-Jersey City,10023,3,NY,1
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1042.0,1058.0,1010.0,1010.0,1010.0,1055.0,1078.0,1022.0,1078.0,1088.0,1080.0,1055.0,1052.0,1050.0,1034.0,1000.0,1000.0,980.0,1032.5,1004.5,1019.5,1005.0,985.0,1021.0,1020.0,1020.0,1020.0,1063.5,1000.0,1000.0,985.0,1029.0,1039.0,1205.0,1057.0,1095.0,1104.0,1127.0,1225.0,1175.0,1082.0,1045.0,1081.0,1058.0,1119.0,1134.5,1097.0,1119.0,1175.0,1165.0,1124.0,1190.0,1202.5,1179.0,1175.0,1179.0,1175.0,1190.0,1205.0,1200.0,1178.0,1209.0,1209.0,1177.0,1245.0,1213.0,1144.0,1159.0,1159.0,1155.0,1152.5,1194.0,1236.5,1201.0,1206.0,1169.0,1157.0,1127.5,Katy,Harris County,Houston-The Woodlands-Sugar Land,77494,4,TX,1
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1250.0,1200.0,1199.0,1175.0,1195.0,1245.0,1265.0,1260.0,1295.0,1300.0,1300.0,1375.0,1375.0,1365.0,1365.0,1350.0,1315.0,1400.0,1435.0,1485.0,1495.0,1495.0,1515.0,1545.0,1500.0,1492.5,1450.0,1450.0,1500.0,1497.5,1450.0,1445.0,1467.5,1450.0,1450.0,1550.0,1525.0,1495.0,1450.0,1435.0,1445.0,1425.0,1395.0,1395.0,1465.0,1500.0,1644.0,1500.0,1525.0,1485.0,1395.0,1475.0,1475.0,1450.0,1425.0,1435.0,1445.0,1425.0,1565.0,1575.0,1550.0,1666.0,1550.0,1525.0,1460.0,1460.0,1455.0,1525.0,1500.0,1450.0,1500.0,1500.0,1575.0,1550.0,1545.0,1495.0,1500.0,1500.0,1535.0,1551.0,1595.0,1595.0,1500.0,1545.0,1575.0,1610.0,1595.0,1600.0,1600.0,1595.0,1577.0,1595.0,1550.0,1550.0,1520.0,1600.0,1650.0,1650.0,1695.0,1675.0,1700.0,1675.0,1720.0,1700.0,1670.0,1625.0,1600.0,Chicago,Cook County,Chicago-Naperville-Elgin,60614,5,IL,1

# Export Aggregated Data

In [75]:
#Set path to export cleaned zillow data
path = r'C:\Users\kishe\Documents\Data Science\Projects\Python Projects\In Progress\Air BnB - SF\SF Airbnb Raw Data - Aggregated\12_29_2019_Zillow_Raw_Aggregated.csv'

#Write zillow to csv file
zillow.to_csv(path, sep=',')